// Demonstration records. Replace this module with a paginated API adapter as the marketplace grows.
export const creators = [
  { id: 'maya', name: 'Maya Thompson', handle: '@mayainmotion', category: 'Lifestyle', location: 'Los Angeles, US', followers: '42.8K', engagement: '5.8%', price: 150, rating: 4.9, reviews: 38, tier: 'Rising talent', image: '/images/lifestyle.jpg', description: 'Everyday moments, thoughtfully told. I create warm, relatable lifestyle videos that help people discover their next favorite brand.', deliverable: '1 Instagram Reel · 30–60 seconds', turnaround: '5 days', platform: 'Instagram', color: 'peach' },
  { id: 'alex', name: 'Alex Rivera', handle: '@alexcreates', category: 'Travel', location: 'Austin, US', followers: '128K', engagement: '4.6%', price: 450, rating: 4.9, reviews: 64, tier: 'Professional', image: '/images/travel.jpg', description: 'Cinematic stories for places worth exploring. I work with travel and outdoor brands to make memorable, adventure-led content.', deliverable: '1 Instagram Reel · 30–60 seconds', turnaround: '7 days', platform: 'Instagram', color: 'blue' },
  { id: 'sofia', name: 'Sofia Chen', handle: '@sofiaglow', category: 'Beauty', location: 'New York, US', followers: '86.2K', engagement: '6.2%', price: 280, rating: 5.0, reviews: 52, tier: 'Established', image: '/images/beauty.jpg', description: 'A fresh perspective on beauty. From skincare routines to product stories, I make thoughtful content for an engaged beauty community.', deliverable: '1 Instagram Reel · 30–60 seconds', turnaround: '5 days', platform: 'Instagram', color: 'pink' },
];

export const companies = [
  { id: 'daily', name: 'Daily Ritual', category: 'Lifestyle', initials: 'dr.', budget: '$150–$400', title: 'Make the everyday a little better', description: 'Looking for lifestyle creators to share an authentic morning routine featuring our home essentials.', color: 'peach' },
  { id: 'roam', name: 'Roam Outdoors', category: 'Travel', initials: 'roam', budget: '$400–$800', title: 'Your next adventure starts here', description: 'Bring our new everyday backpack along on a weekend escape. Open to travel and outdoor creators.', color: 'blue' },
  { id: 'bloom', name: 'Bloom Skin', category: 'Beauty', initials: 'b.', budget: '$200–$500', title: 'Real skin. Real stories.', description: 'Seeking beauty creators for honest, creative content around a simple, everyday skincare routine.', color: 'pink' },
];
